# Generated by Django 4.2.5 on 2023-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighttemplatefiles',
            name='template_file',
            field=models.FileField(upload_to='', verbose_name='Template Source Codes(ZIP)'),
        ),
        migrations.AlterField(
            model_name='eighttemplatefiles',
            name='template_image1',
            field=models.FileField(upload_to='', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='eighttemplatefiles',
            name='template_image2',
            field=models.FileField(upload_to='', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='eighttemplatefiles',
            name='template_image3',
            field=models.FileField(upload_to='', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='eighttemplatefiles',
            name='template_image4',
            field=models.FileField(upload_to='', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='eighttemplatefiles',
            name='template_image5',
            field=models.FileField(upload_to='', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='eighttemplatefiles',
            name='template_image6',
            field=models.FileField(upload_to='', verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='eighttemplatefiles',
            name='template_image7',
            field=models.FileField(upload_to='', verbose_name='Image 7'),
        ),
        migrations.AlterField(
            model_name='eighttemplatefiles',
            name='template_image8',
            field=models.FileField(upload_to='', verbose_name='Image 8'),
        ),
        migrations.AlterField(
            model_name='fivetemplatefiles',
            name='cover_photo',
            field=models.FileField(upload_to='', verbose_name='Your Cover Photo'),
        ),
        migrations.AlterField(
            model_name='fivetemplatefiles',
            name='template_file',
            field=models.FileField(upload_to='', verbose_name='Template Source Codes(ZIP)'),
        ),
        migrations.AlterField(
            model_name='fivetemplatefiles',
            name='template_image1',
            field=models.FileField(upload_to='', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='fivetemplatefiles',
            name='template_image2',
            field=models.FileField(upload_to='', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='fivetemplatefiles',
            name='template_image3',
            field=models.FileField(upload_to='', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='fivetemplatefiles',
            name='template_image4',
            field=models.FileField(upload_to='', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='fivetemplatefiles',
            name='template_image5',
            field=models.FileField(upload_to='', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='cover_photo',
            field=models.FileField(upload_to='', verbose_name='Your Cover Photo'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_file',
            field=models.FileField(upload_to='', verbose_name='Template Source Codes(ZIP)'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_image1',
            field=models.FileField(upload_to='', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_image2',
            field=models.FileField(upload_to='', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_image3',
            field=models.FileField(upload_to='', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_image4',
            field=models.FileField(upload_to='', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_image5',
            field=models.FileField(upload_to='', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_image6',
            field=models.FileField(upload_to='', verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_image7',
            field=models.FileField(upload_to='', verbose_name='Image 7'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_image8',
            field=models.FileField(upload_to='', verbose_name='Image 8'),
        ),
        migrations.AlterField(
            model_name='ninetemplatefiles',
            name='template_image9',
            field=models.FileField(upload_to='', verbose_name='Image 9'),
        ),
        migrations.AlterField(
            model_name='onetemplatefiles',
            name='template_image1',
            field=models.FileField(upload_to='', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='seventemplatefiles',
            name='cover_photo',
            field=models.FileField(upload_to='', verbose_name='Your Cover Photo'),
        ),
        migrations.AlterField(
            model_name='seventemplatefiles',
            name='template_image1',
            field=models.FileField(upload_to='', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='seventemplatefiles',
            name='template_image2',
            field=models.FileField(upload_to='', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='sixtemplatefiles',
            name='cover_photo',
            field=models.FileField(upload_to='', verbose_name='Your Cover Photo'),
        ),
        migrations.AlterField(
            model_name='sixtemplatefiles',
            name='template_file',
            field=models.FileField(upload_to='', verbose_name='Template Source Codes(ZIP)'),
        ),
        migrations.AlterField(
            model_name='sixtemplatefiles',
            name='template_image1',
            field=models.FileField(upload_to='', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='sixtemplatefiles',
            name='template_image2',
            field=models.FileField(upload_to='', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='sixtemplatefiles',
            name='template_image3',
            field=models.FileField(upload_to='', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='sixtemplatefiles',
            name='template_image4',
            field=models.FileField(upload_to='', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='sixtemplatefiles',
            name='template_image5',
            field=models.FileField(upload_to='', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='sixtemplatefiles',
            name='template_image6',
            field=models.FileField(upload_to='', verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='cover_photo',
            field=models.FileField(upload_to='', verbose_name='Your Cover Photo'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_file',
            field=models.FileField(upload_to='', verbose_name='Template Source Codes(ZIP)'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image1',
            field=models.FileField(upload_to='', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image10',
            field=models.FileField(upload_to='', verbose_name='Image 10'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image2',
            field=models.FileField(upload_to='', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image3',
            field=models.FileField(upload_to='', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image4',
            field=models.FileField(upload_to='', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image5',
            field=models.FileField(upload_to='', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image6',
            field=models.FileField(upload_to='', verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image7',
            field=models.FileField(upload_to='', verbose_name='Image 7'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image8',
            field=models.FileField(upload_to='', verbose_name='Image 8'),
        ),
        migrations.AlterField(
            model_name='tentemplatefiles',
            name='template_image9',
            field=models.FileField(upload_to='', verbose_name='Image 9'),
        ),
        migrations.AlterField(
            model_name='threetemplatefiles',
            name='cover_photo',
            field=models.FileField(upload_to='', verbose_name='Your Cover Photo'),
        ),
        migrations.AlterField(
            model_name='threetemplatefiles',
            name='template_file',
            field=models.FileField(upload_to='', verbose_name='Template Source Codes(ZIP)'),
        ),
        migrations.AlterField(
            model_name='threetemplatefiles',
            name='template_image1',
            field=models.FileField(upload_to='', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='threetemplatefiles',
            name='template_image2',
            field=models.FileField(upload_to='', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='threetemplatefiles',
            name='template_image3',
            field=models.FileField(upload_to='', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Your Cover Photo'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Template Source Codes(ZIP)'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image10',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 10'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image4',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image5',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image6',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image7',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 7'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image8',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 8'),
        ),
        migrations.AlterField(
            model_name='webtemplates',
            name='template_image9',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 9'),
        ),
    ]
